  import { Roboto } from 'next/font/google'
import "./globals.css";
import ComponenteLogo from "@/components/componenteLogo/ComponenteLogo";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "VISTORIA - PORTO SEGURO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
      <ComponenteLogo />
        {children}
      </body>
    </html>
  );
}
