import { Inter } from 'next/font/google'
import './globals.css'
import ComponenteLogo from '@/components/Logo/ComponenteLogo'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'VISTORIA - PORTO SEGURO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ComponenteLogo/>
          {children}
        
      </body>
    </html>
  )
}
